name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: Run coverage
        run: go test --race --coverprofile=coverage.out --covermode=atomic
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: curl -k "https://codecov.io/bash" > codecov.sh && chmod +x ./codecov.sh && ./codecov.sh -t "$CODECOV_TOKEN"